name: Backup Workflow

on:
  push:
    branches:
      - '**-test' # Exec workflow on every branch that finish with '-test'
  schedule:
    - cron: '0 * * * *' # Exec every hour
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest # Run workflow with Ubuntu environnement

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Clone and checkout branch

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1 # Setup Docker build as it's entilted

      - name: Build Docker image
        run: docker build -t backup-script . # Build up the Docker image from Dockerfile and it will be named "backup-script"

      - name: Run Docker container
        run: docker run -v $(pwd)/data:/usr/src/app/data backup-script # Run Docker container

      # Exec git commands
      - name: Commit and push backups
        run: |
          git config --global user.name "Paul"
          git config --global user.email "p.damquangthanh@gmail.com"
          git add data/
          git commit -m "Backup: $(date)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}